export interface GithubRepoItem {
  readonly allow_forking: Boolean;
  readonly archive_url: string;
  readonly archived: Boolean;
  readonly assignees_url: string;
  readonly blobs_url: string;
  readonly branches_url: string;
  readonly clone_url: string;
  readonly collaborators_url: string;
  readonly comments_url: string;
  readonly commits_url: string;
  readonly compare_url: string;
  readonly contents_url: string;
  readonly contributors_url: string;
  readonly created_at: string;
  readonly default_branch: string;
  readonly deployments_url: string;
  readonly description: string;
  readonly disabled: Boolean;
  readonly downloads_url: string;
  readonly events_url: string;
  readonly fork: Boolean;
  readonly forks: 2;
  readonly forks_count: 2;
  readonly forks_url: string;
  readonly full_name: string;
  readonly git_commits_url: string;
  readonly git_refs_url: string;
  readonly git_tags_url: string;
  readonly git_url: string;
  readonly has_discussions: Boolean;
  readonly has_downloads: Boolean;
  readonly has_issues: Boolean;
  readonly has_pages: Boolean;
  readonly has_projects: Boolean;
  readonly has_wiki: Boolean;
  readonly homepage: null;
  readonly hooks_url: string;
  readonly html_url: string;
  readonly id: number | string;
  readonly is_template: Boolean;
  readonly issue_comment_url: string;
  readonly issue_events_url: string;
  readonly issues_url: string;
  readonly keys_url: string;
  readonly labels_url: string;
  readonly language: string;
  readonly languages_url: string;
  readonly license: null;
  readonly merges_url: string;
  readonly milestones_url: string;
  readonly mirror_url: null;
  readonly name: string;
  readonly node_id: string;
  readonly notifications_url: string;
  readonly open_issues: number;
  readonly open_issues_count: number;
  owner: {
    readonly avatar_url: string;
    readonly events_url: string;
    readonly followers_url: string;
    readonly following_url: string;
    readonly gists_url: string;
    readonly gravatar_id: string;
    readonly html_url: string;
    readonly id: number;
    readonly login: string;
    readonly node_id: string;
    readonly organizations_url: string;
    readonly received_events_url: string;
    readonly repos_url: string;
    readonly site_admin: Boolean;
    readonly starred_url: string;
    readonly subscriptions_url: string;
    readonly type: string;
    readonly url: string;
  };
  permissions: {
    readonly admin: Boolean;
    readonly maintain: Boolean;
    readonly pull: Boolean;
    readonly push: Boolean;
    readonly triage: Boolean;
  };
  readonly private: Boolean;
  readonly pulls_url: string;
  readonly pushed_at: string;
  readonly releases_url: string;
  readonly size: number;
  readonly ssh_url: string;
  stargazers_count: number;
  readonly stargazers_url: string;
  readonly statuses_url: string;
  readonly subscribers_url: string;
  readonly subscription_url: string;
  readonly svn_url: string;
  readonly tags_url: string;
  readonly teams_url: string;
  readonly topics: [];
  readonly trees_url: string;
  readonly updated_at: string;
  readonly url: string;
  readonly visibility: string;
  readonly watchers: number;
  readonly watchers_count: number;
  readonly web_commit_signoff_required: Boolean;
}

export interface RepoToPostType {
  readonly createdAt: string;
  readonly fullName: string;
  readonly id: string | number;
  readonly language: string;
  readonly stargazersCount: number;
  readonly url: string;
}
